### ISSUE TITLE
アマン京都用github作成

### ISSUE THREAD

**Issue by noriemitsuka** [noriemitsuka/sakatayoshiko-muraao125#1]

**Comment by noriemitsuka** [comment]
@sakatayoshiko
メール届きましたか？

**Comment by sakatayoshiko** [comment]
@noriemitsuka 
見ました

**Comment by noriemitsuka** [comment]
@muraao125
メール届きましたか？

**Comment by noriemitsuka** [comment]
@sakatayoshiko @muraao125

@をつけてアカウント名を入れれば、
メールにて更新内容を相手に送ることができるので、
見落としも無いと思います。

**Comment by noriemitsuka** [comment]
@sakatayoshiko 
イシューを立てて、先日送ってもらったエクセルを、
コメント欄にドランキングして、掲載してみてください。

**Comment by muraao125** [comment]
届きました。

**Comment by noriemitsuka** [comment]
@sakatayoshiko @muraao125
その話題になっている案件が終わったら、左下のcloseボタンを押せば大丈夫です。

それでは、設定完了しましたので、
このイシューはクローズします。
